### ISSUE TITLE
Freelance work

### ISSUE THREAD

**Issue by VersaceXcodes** [FurkannM/bolt.new-extended#1]
are you available for paid freelance work? if so how can I contact you? thanks @FurkannM

**Comment by FurkannM** [comment]
Hi! Thanks for reaching out. Yes, I am open to freelance opportunities. You can contact me via furkannmercimek@gmail.com. Looking forward to hearing from you!

**Comment by VersaceXcodes** [comment]
I sent an email there thanks @FurkannM do you have twitter or discord?
